// <auto-generated />
using System;
using DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(WineManagementSystemContext))]
    partial class WineManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataLayer.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Account_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierId");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.Wine", b =>
                {
                    b.Property<int>("WineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Wine_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WineId"), 1L, 1);

                    b.Property<decimal?>("AlcContent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("WineId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Wine", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.WineBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Batch_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"), 1L, 1);

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("Request_Id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WineId")
                        .HasColumnType("int")
                        .HasColumnName("Wine_Id");

                    b.HasKey("BatchId")
                        .HasName("PK__WineBatc__28E47C73F89C0FAE");

                    b.HasIndex("RequestId");

                    b.HasIndex("WineId");

                    b.ToTable("WineBatch", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.WineImportCheck", b =>
                {
                    b.Property<int>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Check_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckId"), 1L, 1);

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("Batch_Id");

                    b.Property<DateTime?>("CheckDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImageURL");

                    b.Property<int?>("InspectorId")
                        .HasColumnType("int")
                        .HasColumnName("Inspector_Id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("Request_Id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WineId")
                        .HasColumnType("int")
                        .HasColumnName("Wine_Id");

                    b.HasKey("CheckId")
                        .HasName("PK__WineImpo__7063BF739B460838");

                    b.HasIndex("BatchId");

                    b.HasIndex("RequestId");

                    b.HasIndex("WineId");

                    b.ToTable("WineImportCheck", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.WineImportRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Request_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("Manager_Id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestData")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Id");

                    b.Property<int?>("WineId")
                        .HasColumnType("int")
                        .HasColumnName("Wine_Id");

                    b.HasKey("RequestId")
                        .HasName("PK__WineImpo__E9C5B37369DF6DBB");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WineId");

                    b.ToTable("WineImportRequest", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.WineStorageLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Location_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<string>("ShelfCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId")
                        .HasName("PK__WineStor__D2BA00E22F2DA2F2");

                    b.ToTable("WineStorageLocation", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.WineTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Transaction_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("Batch_Id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImageURL");

                    b.Property<int?>("InspectorId")
                        .HasColumnType("int")
                        .HasColumnName("Inspector_Id");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("Location_Id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("date");

                    b.Property<string>("TransType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WineId")
                        .HasColumnType("int")
                        .HasColumnName("Wine_Id");

                    b.HasKey("TransactionId")
                        .HasName("PK__WineTran__9A8D5605092A147D");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId");

                    b.HasIndex("WineId");

                    b.ToTable("WineTransaction", (string)null);
                });

            modelBuilder.Entity("DataLayer.Models.Account", b =>
                {
                    b.HasOne("DataLayer.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Account__Role_Id__267ABA7A");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataLayer.Models.Wine", b =>
                {
                    b.HasOne("DataLayer.Models.Category", "Category")
                        .WithMany("Wines")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Wine__Category_I__2D27B809");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataLayer.Models.WineBatch", b =>
                {
                    b.HasOne("DataLayer.Models.WineImportRequest", "Request")
                        .WithMany("WineBatches")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__WineBatch__Reque__34C8D9D1");

                    b.HasOne("DataLayer.Models.Wine", "Wine")
                        .WithMany("WineBatches")
                        .HasForeignKey("WineId")
                        .HasConstraintName("FK__WineBatch__Wine___33D4B598");

                    b.Navigation("Request");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("DataLayer.Models.WineImportCheck", b =>
                {
                    b.HasOne("DataLayer.Models.WineBatch", "Batch")
                        .WithMany("WineImportChecks")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__WineImpor__Batch__3F466844");

                    b.HasOne("DataLayer.Models.WineImportRequest", "Request")
                        .WithMany("WineImportChecks")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK__WineImpor__Reque__3E52440B");

                    b.HasOne("DataLayer.Models.Wine", "Wine")
                        .WithMany("WineImportChecks")
                        .HasForeignKey("WineId")
                        .HasConstraintName("FK__WineImpor__Wine___403A8C7D");

                    b.Navigation("Batch");

                    b.Navigation("Request");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("DataLayer.Models.WineImportRequest", b =>
                {
                    b.HasOne("DataLayer.Models.Supplier", "Supplier")
                        .WithMany("WineImportRequests")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__WineImpor__Suppl__300424B4");

                    b.HasOne("DataLayer.Models.Wine", "Wine")
                        .WithMany("WineImportRequests")
                        .HasForeignKey("WineId")
                        .HasConstraintName("FK__WineImpor__Wine___30F848ED");

                    b.Navigation("Supplier");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("DataLayer.Models.WineTransaction", b =>
                {
                    b.HasOne("DataLayer.Models.WineBatch", "Batch")
                        .WithMany("WineTransactions")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__WineTrans__Batch__398D8EEE");

                    b.HasOne("DataLayer.Models.WineStorageLocation", "Location")
                        .WithMany("WineTransactions")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__WineTrans__Locat__3B75D760");

                    b.HasOne("DataLayer.Models.Wine", "Wine")
                        .WithMany("WineTransactions")
                        .HasForeignKey("WineId")
                        .HasConstraintName("FK__WineTrans__Wine___3A81B327");

                    b.Navigation("Batch");

                    b.Navigation("Location");

                    b.Navigation("Wine");
                });

            modelBuilder.Entity("DataLayer.Models.Category", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("DataLayer.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("DataLayer.Models.Supplier", b =>
                {
                    b.Navigation("WineImportRequests");
                });

            modelBuilder.Entity("DataLayer.Models.Wine", b =>
                {
                    b.Navigation("WineBatches");

                    b.Navigation("WineImportChecks");

                    b.Navigation("WineImportRequests");

                    b.Navigation("WineTransactions");
                });

            modelBuilder.Entity("DataLayer.Models.WineBatch", b =>
                {
                    b.Navigation("WineImportChecks");

                    b.Navigation("WineTransactions");
                });

            modelBuilder.Entity("DataLayer.Models.WineImportRequest", b =>
                {
                    b.Navigation("WineBatches");

                    b.Navigation("WineImportChecks");
                });

            modelBuilder.Entity("DataLayer.Models.WineStorageLocation", b =>
                {
                    b.Navigation("WineTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
